name: Run Pre-Commit Hooks

description: Run pre-commit hooks

inputs:
  # either pass in a token, or an app id and private key
  token:
    description: "The GitHub token to use for authentication"
    required: false
  application_id:
    description: "The GitHub App ID"
    required: false
  application_private_key:
    description: "The GitHub App private key"
    required: false
  check-type:
    description: The type of check to run. Valid values are "all", "common", "terraform", "golang", and "renovate"
    required: true
    default: all
  buildharness_version:
    description: The version of buildharness used by the caller repo
    required: true
  golang_version:
    description: The version of golang used by the buildharness release from the caller repo
    required: true

runs:
  using: composite
  steps:
    - name: Get token
      id: get_installation_token
      uses: peter-murray/workflow-application-token-action@d17e3a9a36850ea89f35db16c1067dd2b68ee343 # v4
      if: ${{ !inputs.token }}
      with:
        application_id: ${{ inputs.application_id }}
        application_private_key: ${{ inputs.application_private_key }}

    - name: Checkout caller repo for processing this action
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        token: ${{ inputs.token || steps.get_installation_token.outputs.token }}
        repository: ${{ github.event.client_payload.pull_request.head.repo.full_name || github.repository }}
        ref: ${{ github.event.client_payload.pull_request.head.ref || github.ref }}

    - name: Init pre-commit cache
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
      with:
        path: "${{ github.workspace }}/.cache/pre-commit"
        key: "${{inputs.check-type}}|${{hashFiles('.pre-commit-config.yaml')}}"

    - name: Init gopath cache
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
      if: contains(inputs.check-type,'golang')
      with:
        path: "${{ github.workspace }}/.cache/go"
        key: "gopath|${{ inputs.golang_version }}|${{ hashFiles('go.sum') }}"

    - name: Init gobuild cache
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
      if: contains(inputs.check-type,'golang')
      with:
        path: "${{ github.workspace }}/.cache/go-build"
        key: "gobuild|${{ inputs.golang_version }}|${{ hashFiles('go.sum') }}"

    - name: Init docker cache
      id: init-docker-cache
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
      with:
        path: "${{ github.workspace }}/.cache/docker"
        key: "docker|${{ inputs.buildharness_version }}"

    - name: Docker save build harness
      if: steps.init-docker-cache.outputs.cache-hit != 'true'
      shell: bash -e -o pipefail {0}
      run: |
        make docker-save-build-harness

    - name: Load build harness
      shell: bash -e -o pipefail {0}
      run: |
        make docker-load-build-harness

    - name: Run `pre-commit check`
      shell: bash -e -o pipefail {0}
      run: "make ${{ inputs.check-type }} fix-cache-permissions"
