name: Update Slash Command Dispatch Comment

description: Update Slash Command Dispatch comment with the run URL

inputs:
  # either pass in a token, or an app id and private key
  token:
    description: 'The GitHub token to use for authentication'
    required: false
  application_id:
    description: 'The GitHub App ID'
    required: false
  application_private_key:
    description: 'The GitHub App private key'
    required: false

runs:
  using: composite
  steps:

    - name: Get token
      id: get_installation_token
      uses: peter-murray/workflow-application-token-action@dc0413987a085fa17d19df9e47d4677cf81ffef3 # v3
      if: ${{ !inputs.token }}
      with:
        application_id: ${{ inputs.application_id }}
        application_private_key: ${{ inputs.application_private_key }}

    - name: Create URL to the run output
      id: vars
      shell: bash -e -o pipefail {0}
      run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

    # Will update the comment that triggered the /test comment and add the run-url
    - name: Update comment
      if: github.event_name == 'repository_dispatch'
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ inputs.token || steps.get_installation_token.outputs.token }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        body: |
          :robot: [View pipeline run][1]

          [1]: ${{ steps.vars.outputs.run-url }}
